version: '2'
networks:
  dev:
volumes:
  mysqldata:
  gaedata:
services:
  mysql:
    image: mysql:5.5
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=greenday_v2"
      - "MYSQL_USER=greenday"
      - "MYSQL_PASSWORD=greenday"
    ports:
      - "3306:3306"
    volumes:
      - "mysqldata:/var/lib/mysql"
    networks:
      - dev
  montage:
    build: .
    volumes:
      - ".:/app"
      - "gaedata:/app/data"
      - /app/parts
      - /app/bin
      - /app/GREENDAY
      - /app/appengine/src/greenday_public/static-dev/libs
      - /app/appengine/src/greenday_public/static-dev/css
      - /app/appengine/src/greenday_public/static/img
      - /app/reports
      - /app/target
      - /app/eggs
      - /app/develop-eggs
      - /app/node_modules
      - /app/appengine/lib
    environment:
      CURRENT_VERSION_ID: local
      DJANGO_SETTINGS_MODULE: greenday_core.settings.local
    depends_on:
      - "mysql"
      - "pender"
    ports:
      - "8080:8080"
      - "8082:8082"
      - "8000:8000"
    networks:
      - dev
  pender:
    build: pender
    shm_size: 1G
    ports:
      - "3200:3200"
      - "9555:9555"
    volumes:
      - "./pender:/app"
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
    networks:
      - dev
