default:
  - 'dev'
  - 'watch'

server:
  - 'dev'
  - 'concurrent:watch'

dev:
  - 'useminlist:html'
  - 'glue:dev'
  - 'sass:dev'
  - 'autoprefixer:dev'
  - 'jshint:dev'
  - 'ngtemplates'
  # - 'karma:unit:start'

build:
  - 'clean:tmp'
  - 'jshint:dist'
  - 'ngtemplates'
  - 'glue:dist'
  - 'sass:dist'
  - 'autoprefixer:dist'
  - 'useminPrepare'
  - 'concat:generated'
  - 'cssmin:generated'
  - 'ngAnnotate:dist'
  - 'uglify:js'
  - 'copy:images'
  - 'copy:fonts'
  - 'clean:tmp'

deployQa:
  - 'clean:static'
  - 'build'
  - 'exec:deployQa'
  - 'clean:static'

deployLive:
  - 'clean:static'
  - 'build'
  - 'exec:deployLive'
  - 'clean:static'

migrateQa:
  - 'exec:migrateQa'

migrateLive:
  - 'exec:migrateLive'

authenticate:
  - 'exec:authenticate'
